# Invoke from gcloud shell with :
#    gcloud builds submit --config cloudbuild.yaml ../../../docker/image/prpl-builder

steps:
# Build the image (Dockerfile will git clone then make)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_PRPL_DOCKER_REGISTRY_HOSTNAME}/${_PRPL_GCP_PROJECT_NAME}/prpl-builder:${COMMIT_SHA}', '-t', '${_PRPL_DOCKER_REGISTRY_HOSTNAME}/${_PRPL_GCP_PROJECT_NAME}/prpl-builder:latest', '-f', 'Dockerfile', '.']
  timeout: 600s
  
substitutions:
    _PRPL_DOCKER_REGISTRY_HOSTNAME: 'eu.gcr.io'
    _PRPL_GCP_PROJECT_NAME: 'davidcallen'
    _PRPL_DOCKER_IMAGE_TAG: ''

images: [ '${_PRPL_DOCKER_REGISTRY_HOSTNAME}/${_PRPL_GCP_PROJECT_NAME}/prpl-builder' ]

options:
  substitution_option: 'ALLOW_LOOSE'  
