# Invoke from gcloud shell with :
#    gcloud builds submit --config cloudbuild.yaml ../../../docker/image/prpl-builder

steps:
# Build the image (Dockerfile will git clone then make)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/davidcallen/prpl-builder:${COMMIT_SHA}', '-t', 'eu.gcr.io/davidcallen/prpl-builder:latest', '-f', 'Dockerfile', '.']
  timeout: 600s
  
substitutions:
    _PRPL_DOCKER_IMAGE_TAG: ''

images: [ 'eu.gcr.io/davidcallen/prpl-builder' ]

options:
  substitution_option: 'ALLOW_LOOSE'  
