podTemplate(label: 'mypod', 
	containers: [
		containerTemplate(name: 'git', image: 'alpine/git', ttyEnabled: true, command: 'cat'),
		containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true),
	],
	volumes: [
			hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
	]
) {
	node('mypod') {
		stage('Check running containers') {
			container('docker') {
				sh """
					set -o errexit
					set -o nounset
					hostname
					hostname -i
					echo
					docker images | grep prpl- || true
				"""
			}
		}
		stage('Clone repository') {
			container('git') {
				sh """whoami
					set -o errexit
					set -o nounset
					hostname -i
					echo PWD=\$PWD
					git clone -b master https://github.com/davidcallen/parkrunpointsleague.git prpl
					ls -la prpl
					cd prpl/deploy/docker/image/prpl-builder
					touch xxxxxxxxxx-test.txt
					cd ../prpl-base
					touch xxxxxxxxxx-prpl-base.test
				"""
				
			}
		}
		stage('Build docker image : prpl-builder') {
			container('docker') {
			sh """
					set -o errexit
					set -o nounset
					set -x
					echo PWD=\$PWD
					ls -la
					cd prpl/deploy/docker/image/prpl-builder
					ls -la
					PRPL_DOCKER_IMAGE_NAME=prpl-builder
					export PRPL_DOCKER_BUILD_DATE=`date`
					export PRPL_DOCKER_IMAGE_TAG=`date +%Y%m%d%H%M%S`
					echo \${PRPL_DOCKER_IMAGE_TAG} > DOCKER_IMAGE_TAG
					echo "Building image \${PRPL_DOCKER_IMAGE_NAME} for tag \${PRPL_DOCKER_IMAGE_TAG}"
					echo
					echo -e "\n----------------------------------- Build image  ---------------------------------------------\n"
					docker rmi \${PRPL_DOCKER_REGISTRY}\${PRPL_DOCKER_IMAGE_NAME} || true
					echo
					docker build \
						--tag=\${PRPL_DOCKER_REGISTRY}\${PRPL_DOCKER_IMAGE_NAME}:\${PRPL_DOCKER_IMAGE_TAG} \
						--tag=\${PRPL_DOCKER_REGISTRY}\${PRPL_DOCKER_IMAGE_NAME}:latest \
						--file=./Dockerfile .
					echo
					docker images | grep prpl- || true
			"""
			}
		}
	}
}
