
# amazon_cloudwatch_agent : installation and configuration of agent
#  Forked from Ansible Galaxy https://galaxy.ansible.com/christiangda/amazon_cloudwatch_agent
#  Forked to fix virtualbox build and suppress startup in non-AWS environment.
- src: git@github.com:davidcallen/ansible-role-amazon-cloudwatch-agent.git
  scm: git

# telegraf : Installs and configures telegraf agent
# Forked from
#   https://galaxy.ansible.com/rossmcdonald/telegraf
#   https://github.com/rossmcdonald/telegraf
# Forked to add ability to :
#  1) Split telegraf.conf into individual conf files. This makes it easier to update/replace those files at initial-startup of the EC2 instance.
#  2) Add var telegraf_enabled_service to allow for install but disabled service.
- src: https://github.com/davidcallen/telegraf.git
  scm: git
  version: master

# epel_repo : contains 'daemonize' package which is required by jenkins rpm
#  from Ansible Galaxy https://galaxy.ansible.com/geerlingguy/repo-epel
- src: geerlingguy.repo-epel
  version: 3.1.0

# awscli : installation of aws command line tool
#  Forked from Ansible Galaxy :
#     https://galaxy.ansible.com/christiangda/awscli
#     https://github.com/christiangda/ansible-role-awscli
# Forked to fix issue : https://github.com/christiangda/ansible-role-awscli/issues/6
- src: git@github.com:davidcallen/ansible-role-awscli.git
  scm: git
  version: master      # 1.0.2a