apiVersion: apps/v1
kind: Deployment
metadata:
  name: prpl
  labels:
    app: prpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prpl
  template:
    metadata:
      labels:
        app: prpl
    spec:
      containers:
      - name: prpl
        image: ${PRPL_DOCKER_REGISTRY}prpl:${PRPL_DOCKER_IMAGE_TAG}
        env:
        - name: PRPL_HTTP_PORT
          value: "8080"
        - name: PRPL_DATABASE_HOST
          value: "10.106.96.3"
        - name: PRPL_DATABASE_PORT
          value: "3306"
        - name: PRPL_DATABASE_NAME
          value: "PRPL"
        - name: PRPL_DATABASE_USER
          value: "PRPL"
        - name: PRPL_DATABASE_PWD
          valueFrom:
            secretKeyRef:
              name: prpl-secrets
              key: PRPL_DATABASE_PWD
        - name: PRPL_LOGGING_LEVEL
          value: "information"
        - name: PRPL_LOGGING_SHOW_HOSTNAME
          value: "true"
        - name: PRPL_RESULTS_SCRAPING_ENABLED
          value: "false"          
        - name: PRPL_DEBUG_STAY_ALIVE
          value: ""
        - name: PRPL_SLEEP_SECS
          value: "1"
        - name: PRPL_SLEEP_TIMES
          value: "60"
        ports:
        - name: http-port
          containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: http-port
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http-port
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "1"
