apiVersion: v1
kind: Service
metadata:
  name: prpl
  labels:
    app: prpl
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: prpl
  type: LoadBalancer
  loadBalancerIP: 35.189.99.129
