USE PRPL;

DROP TABLE IF EXISTS ATHLETE;

DROP TABLE IF EXISTS EVENT;

DROP TABLE IF EXISTS EVENT_RESULT;

DROP TABLE IF EXISTS EVENT_RESULT_ITEM;

DROP TABLE IF EXISTS EVENT_LEAGUE;

DROP TABLE IF EXISTS PARAM;
