use PRPL;
select * from EVENT_RESULT_ITEM where EVENT_RESULT_ID = 160;

insert into EVENT (NAME, TITLE) values ('miltonkeynes', 'Milton Keynes');

select count(*) from EVENT_RESULT;
select count(*) from EVENT_RESULT_ITEM;
select count(*) from EVENT_RESULT_ITEM where EVENT_RESULT_ID = 436;
-- select max(EVENT_RESULT_ID) from EVENT_RESULT_ITEM;
select count(*) from ATHLETE;
select count(*) from EVENT_LEAGUE;

select * from EVENT;
select * from EVENT_RESULT ORDER BY EVENT_ID ASC, RESULT_NUMBER DESC;
select * from EVENT_RESULT_ITEM where EVENT_RESULT_ID = 433 and ATHLETE_ID = 2039918; 
select * from EVENT_RESULT_ITEM where ATHLETE_ID = 2039918; 
-- select max(EVENT_RESULT_ID) from EVENT_RESULT_ITEM;
select * from ATHLETE;
select * from ATHLETE where ID = 74146;
select * from EVENT_LEAGUE ORDER BY EVENT_ID ASC, YEAR DESC;
select * from EVENT_LEAGUE where YEAR = 2016 order by EVENT_ID, YEAR DESC;
select ELI.* from EVENT_LEAGUE_ITEM ELI, EVENT_LEAGUE EL WHERE EL.ID = ELI.EVENT_LEAGUE_ID AND EL.YEAR = 2016 AND EL.EVENT_ID = 2 ORDER BY POSITION ASC;

select * from ATHLETE where ID = 370098;


select EVENT_ID, YEAR, ATHLETE_ID, (SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) FROM ATHLETE WHERE ID = ATHLETE_ID), POINTS, RUN_COUNT 
from EVENT_LEAGUE 
where YEAR = 2015 
order by EVENT_ID, YEAR DESC, POINTS DESC, RUN_COUNT DESC;

USE PRPL;
select distinct(RESULT_NUMBER) from EVENT_RESULT WHERE EVENT_ID = 1 ORDER BY RESULT_NUMBER DESC;
select distinct(EVENT_RESULT_ID) from EVENT_RESULT_ITEM ORDER BY EVENT_RESULT_ID DESC;
select *  from EVENT_RESULT ORDER BY EVENT_ID, RESULT_NUMBER DESC;
select * from EVENT_RESULT_ITEM where ATHLETE_ID = 74146 ORDER BY EVENT_RESULT_ID DESC;
select ER.EVENT_ID, ER.RESULT_NUMBER, ERI.* from EVENT_RESULT_ITEM ERI, EVENT_RESULT ER WHERE ERI.EVENT_RESULT_ID = ER.ID AND ER.EVENT_ID = 1 ORDER BY EVENT_RESULT_ID DESC, POSITION ASC;
select distinct(ER.RESULT_NUMBER) from EVENT_RESULT_ITEM ERI, EVENT_RESULT ER WHERE ERI.EVENT_RESULT_ID = ER.ID AND ER.EVENT_ID = 1 ORDER BY EVENT_RESULT_ID DESC, POSITION ASC;
select ER.EVENT_ID, ER.RESULT_NUMBER, ERI.* from EVENT_RESULT_ITEM ERI, EVENT_RESULT ER WHERE ERI.EVENT_RESULT_ID = ER.ID AND ER.EVENT_ID = 2 and ER.RESULT_NUMBER = 50 ORDER BY EVENT_RESULT_ID DESC, POSITION ASC;

select ER.EVENT_ID, ER.RESULT_NUMBER, ERI.* from EVENT_RESULT_ITEM ERI, EVENT_RESULT ER WHERE ERI.EVENT_RESULT_ID = ER.ID AND ER.EVENT_ID = 2 and ERI.ATHLETE_ID = 74146 ORDER BY EVENT_RESULT_ID DESC, POSITION ASC;

select count(*) from EVENT_RESULT_ITEM ERI, EVENT_RESULT ER WHERE ERI.EVENT_RESULT_ID = ER.ID AND ER.EVENT_ID = 1 and ER.RESULT_NUMBER = 382 ORDER BY EVENT_RESULT_ID DESC, POSITION ASC;

select distinct(YEAR) from EVENT_LEAGUE order by EVENT_ID, YEAR DESC;
select * from EVENT_LEAGUE order by EVENT_ID, YEAR DESC;
select * from EVENT_LEAGUE_ITEM order by EVENT_LEAGUE_ID, POINTS DESC, RUN_COUNT DESC;
select EVENT_LEAGUE_ID, count(*) from EVENT_LEAGUE_ITEM group by EVENT_LEAGUE_ID order by EVENT_LEAGUE_ID, POINTS DESC, RUN_COUNT DESC;

select count(*) from EVENT_RESULT_ITEM where EVENT_RESULT_ID =  440
select * from EVENT_RESULT_ITEM where EVENT_RESULT_ID =  3

-- Remove a bad result
delete from EVENT_RESULT where ID=440;
delete from EVENT_RESULT_ITEM where EVENT_RESULT_ID = 440;
update EVENT_LEAGUE set LATEST_EVENT_RESULT_ID = 381 WHERE YEAR = 2017;


select * from EVENT_RESULT ORDER BY EVENT_ID, RESULT_NUMBER DESC;
-- select * from EVENT_RESULT_ITEM ORDER BY EVENT_RESULT_NUMBER DESC;

delete from EVENT_RESULT where ID=438;
delete from EVENT_RESULT where EVENT_ID = 2 AND RESULT_NUMBER=14;
delete from EVENT_RESULT_ITEM where EVENT_RESULT_ID = 438;
delete from EVENT_LEAGUE where EVENT_ID = 2;
delete from EVENT_LEAGUE_ITEM where EVENT_LEAGUE_ID = 30;
delete from EVENT_LEAGUE;
delete from EVENT_LEAGUE_ITEM;
delete from EVENT where NAME = 'miltonkeynes';


insert into EVENT (NAME, TITLE) values ('linfordwood', 'Linford Wood');
commit;


-- Athlete league position. Filter by Event and Year. Show individual Race Results
use PRPL;
select A.*, EL.*, ELI.* from ATHLETE A, EVENT E, EVENT_LEAGUE EL, EVENT_LEAGUE_ITEM ELI 
where E.ID = EL.EVENT_ID AND EL.ID = ELI.EVENT_LEAGUE_ID AND A.ID = ELI.ATHLETE_ID AND A.ID = 370098 and E.NAME = 'miltonkeynes' and EL.YEAR = 2017

-- Results for a 
select A.*, ER.*, ERI.* from ATHLETE A, EVENT E, EVENT_RESULT ER, EVENT_RESULT_ITEM ERI 
where E.ID = ER.EVENT_ID AND ER.ID = ERI.EVENT_RESULT_ID AND A.ID = ERI.ATHLETE_ID AND A.ID = 370098 and E.NAME = 'miltonkeynes' order by ER.RESULT_NUMBER DESC;


ALTER TABLE EVENT_RESULT ADD COLUMN (
	LEAGUE_YEAR                     INTEGER UNSIGNED
)

ALTER TABLE EVENT_LEAGUE ADD COLUMN (
	LATEST_EVENT_RESULT_ID          INTEGER UNSIGNED NOT NULL
)


ALTER TABLE EVENT_LEAGUE_ITEM ADD COLUMN (
	GENDER_POSITION                 INTEGER UNSIGNED NOT NULL,
	GENDER                          VARCHAR(1) NOT NULL
)

ALTER TABLE EVENT_RESULT_ITEM ADD COLUMN (
	GENDER                          VARCHAR(1) NOT NULL
)
