apiVersion: v1
kind: PersistentVolume
metadata:
  name: prpl-jenkins-pv
  labels:
    app: prpl-jenkins
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prpl-jenkins-pvc
  labels:
    app: prpl-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
